language: objective-c
xcode_project: Faraday.xcodeproj
xcode_scheme: Faraday
xcode_sdk: iphonesimulator9.1
osx_image: xcode7.1
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
